-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 10:48:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `car_wash` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_wash` DEFAULT CHARACTER SET utf8 ;
USE `car_wash` ;

-- -----------------------------------------------------
-- Table `mydb`.`Branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_wash`.`Branch` ;

CREATE TABLE IF NOT EXISTS `car_wash`.`Branch` (
  `id_branch` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_branch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_wash`.`Car` ;

CREATE TABLE IF NOT EXISTS `car_wash`.`Car` (
  `id_car` INT NOT NULL AUTO_INCREMENT,
  `Img` VARCHAR(45) NOT NULL,
  `state` ENUM("arrived", "washed", "drying", "leaving") NOT NULL,
  `plate_id` INT NOT NULL,
  `owner_user_id` INT NOT NULL,
  PRIMARY KEY (`id_car`),
  INDEX `owner_user_id_idx` (`owner_user_id` ASC) VISIBLE,
  INDEX `plate_id_idx` (`plate_id` ASC) VISIBLE,
  UNIQUE INDEX `plate_id_UNIQUE` (`plate_id` ASC) VISIBLE,
  CONSTRAINT `owner_user_id`
    FOREIGN KEY (`owner_user_id`)
    REFERENCES `mydb`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plate_id`
    FOREIGN KEY (`plate_id`)
    REFERENCES `mydb`.`Plate` (`id_plate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_wash`.`Plate` ;

CREATE TABLE IF NOT EXISTS `car_wash`.`Plate` (
  `id_plate` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_plate`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_wash`.`User` ;

CREATE TABLE IF NOT EXISTS `car_wash`.`User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` ENUM("normal", "admin", "employee") NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
